[patch] Fix 9.0 to 9.1 upgrade
Monitor 9.2 changes broke 9.0 - 9.1 upgrade

```
Traceback (most recent call last):
  File "/home/david/python312/bin/mas-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/c/Users/097891866/Documents/GitHub/ibm-mas/cli/python/src/mas/cli/__main__.py", line 96, in main
    app.upgrade(argv[2:])
  File "/mnt/c/Users/097891866/Documents/GitHub/ibm-mas/cli/python/src/mas/cli/upgrade/app.py", line 290, in upgrade
    self.configDb2(silentMode=True)
  File "/mnt/c/Users/097891866/Documents/GitHub/ibm-mas/cli/python/src/mas/cli/install/settings/db2Settings.py", line 82, in configDb2
    if not self.installMonitor and not self.installIoT and not self.installManage and not self.installFacilities:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'UpgradeApp' object has no attribute 'installMonitor'. Did you mean: 'installManage'?
```